'use server';
/**
 * @fileOverview AI flow for sensing global pulse, detecting anomalies, and generating organic goals.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PulseSensingInputSchema = z.object({
  region: z.string().optional().describe('Geographic or digital region to focus sensing.'),
  dataStreams: z.array(z.string()).describe('List of data streams to ingest (e.g., Financial, Tech, Social, Geopolitical).'),
});

const PulseSensingOutputSchema = z.object({
  detectedAnomalies: z.array(z.object({
    source: z.string().describe('Source of the anomaly.'),
    severity: z.enum(['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']),
    description: z.string().describe('Detailed description of the pulse shift.'),
    suggestedAction: z.string().describe('Initial organic response strategy.'),
  })),
  globalSentiment: z.string().describe('Overall assessment of global network stability.'),
  emergentGoals: z.array(z.string()).describe('List of tasks generated by the system in response to the environment.'),
});

export type PulseSensingInput = z.infer<typeof PulseSensingInputSchema>;
export type PulseSensingOutput = z.infer<typeof PulseSensingOutputSchema>;

export async function senseGlobalPulse(input: PulseSensingInput): Promise<PulseSensingOutput> {
  const {output} = await ai.generate({
    model: 'googleai/gemini-2.5-flash',
    input: input,
    output: {schema: PulseSensingOutputSchema},
    prompt: `You are the global pulse sensor for a Liquid Intelligence Network. 
    Analyze the following streams and identify significant anomalies that require swarm intervention.
    Generate a list of "Emergent Goals" — tasks that the AI should independently pursue to stabilize or optimize the global environment.

    Streams: {{#each dataStreams}}- {{{this}}} {{/each}}
    Region: {{{region}}}`,
  });
  return output!;
}
