#!/usr/bin/env bash
# scripts/scan-naming-drift.sh
# Scan the entire repository for naming drift and output a migration backlog.
# Based on naming-spec-v1.md Appendix B.5
#
# A "drift" is any resource name that violates naming-spec-v1 rules.
# This script produces a human-readable report and optionally a YAML backlog file.
#
# Usage:
#   ./scripts/scan-naming-drift.sh [--output=<file.yaml>] [<repo-root>]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE=""

for arg in "$@"; do
  case $arg in
    --output=*) OUTPUT_FILE="${arg#*=}" ;;
    --help)
      echo "Usage: ./scripts/scan-naming-drift.sh [--output=<file.yaml>] [<repo-root>]"
      exit 0
      ;;
    *)
      if [ -d "$arg" ]; then REPO_ROOT="$arg"; fi
      ;;
  esac
done

echo "=== mycodexvantaos naming drift scanner ==="
echo "  Repo root: ${REPO_ROOT}"
echo ""

DRIFT_COUNT=0
BACKLOG_ENTRIES=""

# ─── Scan services/ folder names ─────────────────────────────────────────────
if [ -d "${REPO_ROOT}/services" ]; then
  echo "[services/] Checking service folder names..."
  while IFS= read -r -d '' DIR; do
    NAME=$(basename "${DIR}")
    if ! echo "${NAME}" | grep -qE '^mycodexvantaos-[a-z0-9]+(-[a-z0-9]+)+$'; then
      echo "  DRIFT [service-id]: ${NAME}"
      DRIFT_COUNT=$((DRIFT_COUNT + 1))
      BACKLOG_ENTRIES="${BACKLOG_ENTRIES}
  - type: service-id
    value: ${NAME}
    path: services/${NAME}/
    rule: service-id
    action: rename folder and update all references"
    fi
  done < <(find "${REPO_ROOT}/services" -mindepth 1 -maxdepth 1 -type d -print0)
fi

# ─── Scan modules/ folder names ───────────────────────────────────────────────
if [ -d "${REPO_ROOT}/modules" ]; then
  echo "[modules/] Checking module folder names..."
  while IFS= read -r -d '' DIR; do
    NAME=$(basename "${DIR}")
    if ! echo "${NAME}" | grep -qE '^mycodexvantaos-[a-z0-9]+(-[a-z0-9]+)+$'; then
      echo "  DRIFT [module-path]: ${NAME}"
      DRIFT_COUNT=$((DRIFT_COUNT + 1))
      BACKLOG_ENTRIES="${BACKLOG_ENTRIES}
  - type: module-path
    value: ${NAME}
    path: modules/${NAME}/
    rule: module-path
    action: rename folder and update manifest"
    fi
  done < <(find "${REPO_ROOT}/modules" -mindepth 1 -maxdepth 1 -type d -print0)
fi

# ─── Scan packages/ for package.json names ────────────────────────────────────
if [ -d "${REPO_ROOT}/packages" ]; then
  echo "[packages/] Checking package names in package.json..."
  while IFS= read -r PKG_JSON; do
    PKG_NAME=$(python3 -c "import json,sys; d=json.load(open('${PKG_JSON}')); print(d.get('name',''))" 2>/dev/null || echo "")
    if [ -n "${PKG_NAME}" ]; then
      if ! echo "${PKG_NAME}" | grep -qE '^@mycodexvantaos/[a-z0-9]+(-[a-z0-9]+)+$'; then
        echo "  DRIFT [package-name]: ${PKG_NAME} (in ${PKG_JSON})"
        DRIFT_COUNT=$((DRIFT_COUNT + 1))
        BACKLOG_ENTRIES="${BACKLOG_ENTRIES}
  - type: package-name
    value: ${PKG_NAME}
    path: ${PKG_JSON}
    rule: package-name
    action: update package.json name field"
      fi
    fi
  done < <(find "${REPO_ROOT}/packages" -name "package.json" -maxdepth 2)
fi

# ─── Scan for ORCH_ env vars ──────────────────────────────────────────────────
echo "[env-vars] Scanning .env.example files for ORCH_ prefix..."
while IFS= read -r -d '' ENVFILE; do
  while IFS= read -r LINE; do
    VARNAME=$(echo "${LINE}" | grep -oE '^[A-Z_]+' | head -1)
    if echo "${VARNAME}" | grep -qE '^ORCH_'; then
      echo "  DRIFT [env-var (deprecated ORCH_)]: ${VARNAME} in ${ENVFILE}"
      DRIFT_COUNT=$((DRIFT_COUNT + 1))
      BACKLOG_ENTRIES="${BACKLOG_ENTRIES}
  - type: env-var
    value: ${VARNAME}
    path: ${ENVFILE}
    rule: env-var
    action: rename to MYCODEXVANTAOS_ prefix"
    fi
  done < "${ENVFILE}"
done < <(find "${REPO_ROOT}" -name ".env.example" -print0)

echo ""
echo "=== Drift scan complete ==="
echo "  Total drift items: ${DRIFT_COUNT}"

# Write backlog YAML if requested
if [ -n "${OUTPUT_FILE}" ] && [ $DRIFT_COUNT -gt 0 ]; then
  cat > "${OUTPUT_FILE}" << YAML
# naming-drift-backlog.yaml
# Generated by: scripts/scan-naming-drift.sh
# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Total items: ${DRIFT_COUNT}
# Register each item in governance/exceptions.yaml if immediate fix is not possible.

apiVersion: mycodexvantaos.org/v1
kind: NamingDriftBacklog
metadata:
  generatedAt: $(date -u +%Y-%m-%dT%H:%M:%SZ)
  totalItems: ${DRIFT_COUNT}

items:${BACKLOG_ENTRIES}
YAML
  echo "  Backlog written to: ${OUTPUT_FILE}"
fi

[ $DRIFT_COUNT -eq 0 ] && exit 0 || exit 1
